"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

import sqlite3
from decimal import Decimal

def decimal_converter(value):
    return Decimal(value)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*czt$39^x(#l)omkmz(18_wg03)+8u@&tf=1r&_zuyx38ujbzi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'channels',
    'django.contrib.staticfiles',
    'rest_framework',
    # 'asgi_redis',
    # 'django_crontab',
    'corsheaders',
    'sistem_app',
    'user',
    'publicar_app',
    'chat'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR   /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',

    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# CORS_ALLOWED_ORIGINS = [
#     'http://127.0.0.1:52963',
#     # Agrega aquí los orígenes permitidos para tu aplicación Flutter
# ]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/images/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/images/')
MEDIA_ROOT = os.path.join(BASE_DIR, '/media/')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUHT_USER_MODEL = 'accounts.CustomUser'
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES":[
        "rest_framework.permissions.AllowAny",
    ],
}

ASGI_APPLICATION = 'myproject.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        "CONFIG": {
            "hosts": [('*', 8000)],
        },
    },
}

# CORS_ALLOWED_ORIGINS = (
#     'http://localhost:53976', #Fron-end
#     "http://localhost:8000", #Back-end
# )

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

#settings para enviar correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'colveg23@gmail.com'
EMAIL_HOST_PASSWORD = 'vlginxaaflxxvheg'

#settings para enviar mensajes sms
# otro
CLICKATELL_API_KEY = 'XiTWQUFxQuenlRcWM6kAxA=='
CLICKATELL_API_ID = '59227625699340628a0b12ff656123b6'

# Twlio
TWILIO_ACCOUNT_SID = 'AC6b4d75899a60352922cf690c7af4e2aa'
TWILIO_AUTH_TOKEN = 'f9ee4f930f9f1841310cf85fe30c2ef6'
TWILIO_PHONE_NUMBER = '+13186127444'
#recuperar cuenta colveg twilio = 'RDbcZZAy3jmNemGmxuSPpnXmODVhFsz65-4e2S44'

#settings para el mapa
# MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoiY29sdmVnIiwiYSI6ImNsZmhldXJxZDBpOWEzenF3cGtoNmYxYXEifQ.h0jhKpVYo6t_8uFcoS_uxg'
# MAPBOX_URL = 'https://api.mapbox.com/mapbox-gl-js/v2.4.0/mapbox-gl.js'
# MAPBOX_CSS_URL = 'https://api.mapbox.com/mapbox-gl-js/v2.4.0/mapbox-gl.css'

#Settings para celery 
# Configuración de Celery
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'

CRONJOBS = [
    ('*/1 * * * *', 'sistem_app.cron.MyCronJob')
]


# Configuración de programación de tareas
# CELERY_BEAT_SCHEDULE = {
#     'delete_expired_codes': {
#         'task': 'delete_expired_codes',
#         'schedule': timedelta(minutes=5),
#     },
# }
ASGI_APPLICATION = "Backend.asgi.application"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
    "CONFIG": {
            "hosts": [('127.0.0.1', '*')],
    },
    'ROUTING': 'Backend.routing.channel_routing',
}
