// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for windows - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6GFNxVPUGR9vw7o19rpZplYKfHE9wZiY',
    appId: '1:696273535872:web:ef6351c0d4803f829d3765',
    messagingSenderId: '696273535872',
    projectId: 'colveg-67dae',
    authDomain: 'colveg-67dae.firebaseapp.com',
    storageBucket: 'colveg-67dae.appspot.com',
    measurementId: 'G-KT9KP38ZC7',
    databaseURL: "https://colveg-67dae-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwxegE9Iy-0KWD3Lcw2iukaNBf7ZFmQ_g',
    appId: '1:696273535872:android:02a26399545a310f9d3765',
    messagingSenderId: '696273535872',
    projectId: 'colveg-67dae',
    storageBucket: 'colveg-67dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzduCDetKdztxCeD4w5dqYfMVnUtpI1E',
    appId: '1:696273535872:ios:57be2cec6f8c78ab9d3765',
    messagingSenderId: '696273535872',
    projectId: 'colveg-67dae',
    storageBucket: 'colveg-67dae.appspot.com',
    iosClientId: '696273535872-g8mb3kl5iv12174gc0lgc6v5t0ckf2t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.colveg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzzduCDetKdztxCeD4w5dqYfMVnUtpI1E',
    appId: '1:696273535872:ios:57be2cec6f8c78ab9d3765',
    messagingSenderId: '696273535872',
    projectId: 'colveg-67dae',
    storageBucket: 'colveg-67dae.appspot.com',
    iosClientId: '696273535872-g8mb3kl5iv12174gc0lgc6v5t0ckf2t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.colveg',
  );

   static const FirebaseOptions windows = FirebaseOptions(
    // Agrega las opciones específicas para Windows aquí
    apiKey: 'AIzaSyDzzduCDetKdztxCeD4w5dqYfMVnUtpI1E',
    appId: '1:696273535872:ios:57be2cec6f8c78ab9d3765',
    messagingSenderId: '696273535872',
    projectId: 'colveg-67dae',
    storageBucket: 'colveg-67dae.appspot.com',
  );
}
